PROGRAM MAIN
	USE APF

	IMPLICIT NONE

	INTEGER, TARGET :: COUNT, N
	DOUBLE PRECISION, TARGET :: STEP

	INTEGER, POINTER :: COUNTP, NP
	DOUBLE PRECISION, POINTER :: STEPP

	COUNT = 5
	COUNTP => COUNT
	N = 20
	NP => N
	STEP = 7.5
	STEPP => STEP

	CALL APF_INT_ADD(COUNTP, "-count")
	CALL APF_DBL_ADD(STEPP, "-step")
	CALL APF_INT_ADD(NP, "-n")

	CALL APF_PARSE()

	PRINT *, 'COUNT ', COUNT
	PRINT *, 'STEP ', STEP
	PRINT *, 'N', N
END PROGRAM
